// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_listen from "./routes/api/listen.ts";
import * as $api_update from "./routes/api/update.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $shared_constants from "./routes/shared/constants.ts";
import * as $shared_db from "./routes/shared/db.ts";
import * as $shared_types from "./routes/shared/types.ts";
import * as $game from "./islands/game.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/listen.ts": $api_listen,
    "./routes/api/update.ts": $api_update,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/shared/constants.ts": $shared_constants,
    "./routes/shared/db.ts": $shared_db,
    "./routes/shared/types.ts": $shared_types,
  },
  islands: {
    "./islands/game.tsx": $game,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
